logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8013
  servlet:
    context-path: /sierra
            
spring:
  web:
    locale: ca_ES
  cloud:
    loadbalancer:
      cache:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true 
        web-allow-others: true
  datasource:
    mainDb:
      platform: h2
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:mainDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: user
      password: null
      initialization-mode: always
    #loggerDb:
    #  platform: h2
    #  driver-class-name: org.h2.Driver
    #  url: jdbc:h2:mem:loggerDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #  username: user
    #  password: null
    #  initialization-mode: always
      
    
  jpa:
    #defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  